function [GW_Basin_ID, varargout] = import_GW_Basins_attributes
%% Import data from text file.
% Script for importing data from the following text file:
%
%    B:\GoogleDrive\giorgk_Gdrive\FREP
%    2012-2014\GNLM-CV\Input_Data\attribute_tables\GNLM_GW_Basins_attributes.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/07/02 12:27:18

%% Initialize variables.
filename = 'Input_Data\attribute_tables\GNLM_GW_Basins_attributes.csv';
delimiter = ',';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: text (%s)
%   column3: text (%s)
%	column4: text (%s)
%   column5: text (%s)
%	column6: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
OBJECTID = dataArray{:, 1};
DWR_BASIN_ID = dataArray{:, 2};
SUBBSN_ID = dataArray{:, 3};
GW_Basin_ID = [];
GW_Basin_Name=[];
for i = 1:length(OBJECTID)
    if isempty(SUBBSN_ID{i,1})
        temp = DWR_BASIN_ID{i,1};
        GW_Basin_Name{i,1} = dataArray{1,5}(i);
    else
        temp = SUBBSN_ID{i,1};
        GW_Basin_Name{i,1} = dataArray{1,6}(i);
    end
    
    p = find(temp == '-' | temp == '.');
    temp(:,p) = [];
    
    GW_Basin_ID = [GW_Basin_ID; OBJECTID(i,1) str2double(temp)];
end
%% Clear temporary variable
clearvars filename delimiter startRow formatSpec fileID dataArray ans;
varargout{1} = GW_Basin_Name;